# Fonction cart
# Reset cart
nfe102_resto_resetcart:
    pattern:  /reset  
    defaults: { _controller: Nfe102RestoBundle:Cart:shootcart }
#   requirements: { _method: post }
# Add art in cart    
nfe102_resto_moreart:
    pattern:  /more  
    defaults: { _controller: Nfe102RestoBundle:Cart:addToCart }
    requirements: { _method: post }
# Del one art in cart
nfe102_resto_lessart:
    pattern:  /less  
    defaults: { _controller: Nfe102RestoBundle:Cart:removeFromCart }
    requirements: { _method: post }
# Del art in cart
nfe102_resto_delart:
    pattern:  /del  
    defaults: { _controller: Nfe102RestoBundle:Cart:delart }
    requirements: { _method: post }

nfe102_resto_showCart:
    pattern:  /showcart  
    defaults: { _controller: Nfe102RestoBundle:Cart:showCart, _format: json}
   # requirements: { _method: post }    