nfe102_resto_hellopage:
    pattern:  /hello/{name}
    defaults: { _controller: Nfe102RestoBundle:Default:hello }
    
nfe102_resto_homepage:
    pattern:  /{menu}
    defaults: { _controller: Nfe102RestoBundle:Default:index , menu: 1}

nfe102_resto_cart:
    resource: "cartrouting.yml"
    prefix:   /cart