nfe102_resto_hellopage:
    pattern:  /hello/{name}
    defaults: { _controller: Nfe102RestoBundle:Default:hello }
    
nfe102_resto_homepage:
    pattern:  /{menu}
    defaults: { _controller: Nfe102RestoBundle:Default:index , menu: 1}

nfe102_resto_cart:
    resource: "cartrouting.yml"
    prefix:   /cart
    
nfe102_resto_admin:
    resource: "adminrouting.yml"
    prefix: /admin
    
nfe102_resto_produit:
    resource: "routing/produit.yml"
    prefix: /produit
    
nfe102_resto_cathegorieproduit:
    resource: "routing/cathegorieproduit.yml"
    prefix: /cathegorieproduit
    
nfe102_resto_adresse:
    resource: "routing/adresse.yml"
    prefix: /adresse