nfe102_resto_hellopage:
    pattern:  /hello/{name}
    defaults: { _controller: Nfe102RestoBundle:Default:hello }
    
nfe102_resto_homepage:
    pattern:  /{menu}
    defaults: { _controller: Nfe102RestoBundle:Default:index , menu: 1}

nfe102_resto_cart:
    resource: "cartrouting.yml"
    prefix:   /cart
    
    
nfe102_resto_produit:
    resource: "routing/produit.yml"
    prefix: /produit
    
nfe102_resto_produit_cat:
    resource: "routing/cathegorieproduit.yml"
    prefix: /cathegorieproduit
        
Nfe102RestoBundle_panier:
    resource: "@Nfe102RestoBundle/Resources/config/routing/panier.yml"
    prefix:   /panier
    
Nfe102RestoBundle_adresse:
    resource: "@Nfe102RestoBundle/Resources/config/routing/adresse.yml"
    prefix:   /adresse
        
Nfe102RestoBundle_cmdfac:
    resource: "@Nfe102RestoBundle/Resources/config/routing/cmdfac.yml"
    prefix:   /cmdfac

Nfe102RestoBundle_codespostaux:
    resource: "@Nfe102RestoBundle/Resources/config/routing/codespostaux.yml"
    prefix:   /codespostaux
