parameters:
#    nfe102_resto.example.class: Nfe102\Bundle\RestoBundle\Example

services:
#    nfe102_resto.example:
#        class: %nfe102_resto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
